name: RF Selenium Hub

on: push

jobs:
  test-inside:
    name: Test inside Docker Compose

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Give the browsers time to connect to Selenium Hub
        run: sleep 10

      - name: Run Chrome tests
        run: |
          docker-compose run -T \
            --entrypoint robot \
            -v $(pwd)/test-results:/test-results/ \
            -v $(pwd)/login_tests/:/tests/login_tests/ \
            application \
            -v BROWSER:$BROWSER \
            -v REMOTE_URL:http://selenium-hub:4444/wd/hub \
            -v SERVER:application:7272 \
            --outputdir /test-results/$BROWSER \
            --name $BROWSER \
            /tests/login_tests/
        env:
          BROWSER: chrome

      - name: Run Firefox tests
        run: |
          docker-compose run -T \
            --entrypoint robot \
            -v $(pwd)/test-results:/test-results/ \
            -v $(pwd)/login_tests/:/tests/login_tests/ \
            application \
            -v BROWSER:$BROWSER \
            -v REMOTE_URL:http://selenium-hub:4444/wd/hub \
            -v SERVER:application:7272 \
            --outputdir /test-results/$BROWSER \
            --name $BROWSER \
            /tests/login_tests/
        env:
          BROWSER: firefox

      - name: Combine test results
        if: ${{ always() }}
        run: |
          docker-compose run -T \
            --entrypoint rebot \
            -v $(pwd)/test-results:/test-results/ \
            application \
            --name "Browser Compatibility" \
            --outputdir /test-results \
            /test-results/*/output.xml

      - name: Store generated reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}  # Make sure to always collect the reports
        with:
          name: test-results
          path: test-results/
